### ISSUE TITLE
Informations sur installation du frontend

### ISSUE THREAD

**Issue by masterbalby2** [r3dlight/keysas#66]
Bonjour,

En recherchant comment configurer des stations blanches pour mon entreprise je suis tombé sur ce projet.
J'ai procédé à l'installation de keysas en suivant les instructions du git.

Je bloque au moment d'installer le frontend.
Je me déplace dans keysas/keysas-frontend et lance la commande "**npm install**"

Je récupère les erreurs suivantes :
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @vitejs/plugin-vue@4.3.4
npm ERR! Found: vite@5.2.10
npm ERR! node_modules/vite
npm ERR!   dev vite@"^5.2.10" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.0.0" from @vitejs/plugin-vue@4.3.4
npm ERR! node_modules/@vitejs/plugin-vue
npm ERR!   dev @vitejs/plugin-vue@"^4.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vite@4.5.3
npm ERR! node_modules/vite
npm ERR!   peer vite@"^4.0.0" from @vitejs/plugin-vue@4.3.4
npm ERR!   node_modules/@vitejs/plugin-vue
npm ERR!     dev @vitejs/plugin-vue@"^4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-08-02T13_37_17_596Z-debug-0.log
```
Qu'est-ce-qui bloque.
Merci pour votre aide

**Comment by r3dlight** [comment]
Bonjour,

Pouvez-vous essayer avec les commandes suivantes:
`npm install --legacy-peer-deps`
`npm run build`

**Comment by masterbalby2** [comment]
Merci pour votre réponse rapide.

Voici le résultat de "npm install --legacy-peer-deps"
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vite@5.2.10',
npm WARN EBADENGINE   required: { node: '^18.0.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'rollup@4.17.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0', npm: '>=8.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }

added 88 packages, and audited 89 packages in 5s

15 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

et de "npm run build"
```
> keysas-frontend@2.4.0 build
> vite build

vite v5.2.10 building for production...
✓ 8 modules transformed.
x Build failed in 494ms
error during build:
Error: [vite]: Rollup failed to resolve import "@popperjs/core" from "/root/keysas/keysas-frontend/node_modules/bootstrap/dist/js/bootstrap.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///root/keysas/keysas-frontend/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67620:27)
    at onRollupWarning (file:///root/keysas/keysas-frontend/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67648:9)
    at onwarn (file:///root/keysas/keysas-frontend/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67364:13)
    at file:///root/keysas/keysas-frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18518:13
    at Object.logger [as onLog] (file:///root/keysas/keysas-frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:20166:9)
    at ModuleLoader.handleInvalidResolvedId (file:///root/keysas/keysas-frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19108:26)
    at file:///root/keysas/keysas-frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19066:26
```

**Comment by r3dlight** [comment]
Ok merci pouvez-vous : 
- Supprimer le fichier package-lock.json
- Editer le fichier package.json et remplacer la version de "@vitejs/plugin-vue": "^4.0.0"  par "^5.1.2"
- Refaire un npm i puis un npm audit fix et enfin npm run build

**Comment by masterbalby2** [comment]
super plus d'erreur,
quelle est l'étape suivante pour se connecter au frontend ?
Je ne trouve pas dans la doc
